"""
    *    fibonacci(n)
            - Computes and prints the total of n fibonacci numbers.
            - Computed fibonacci numbers are appended in list.
            - Even numbers sum from the list of fibonacci numbers is computed
              and printed.

    *    fibonacci_upto(n)
            - Computes and prints the fibonacci numbers from 1 to n.
            - Computed fibonacci numbers are appended in list.
            - Even numbers sum from the list of fibonacci numbers is computed
              and printed.

    *    Problem Statement:
            Each new term in the Fibonacci sequence is generated by adding the
            previous two terms. By starting with 1 and 2, the first 10 terms
            will be :
                        1, 2, 3, 5, 13, 21, 34, 55, 89, ...
            By considering the terms in the Fibonacci sequence while values
            do not exceed four million, find the sum of the even valued terms

    *    Test Cases:
        i.    input ->  fibonacci(10)
              output -> Total fibonacci numbers of 10 terms are
                        [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
                        Sum of even numbers is 44

        ii.   input ->  fibonacci_upto(100)
              output -> Fibonacci numbers up to 100 term are
                        [1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
                        Even numbers sum is 44

        iii.  input ->  fibonacci_upto(4000000)
              output -> Fibonacci numbers up to 4000000 term are
                        [1, 2, 3, 5, 8, 13, 21, 34,....., 3524578]
                        Even numbers sum is 4613732

"""

def fibonacci(n):
    a, b, i = 1, 2, 0
    fibonacci_numbers = []
    while i != n:
        fibonacci_numbers.append(a)
        a, b = b, a + b
        i += 1
    print('Total fibonacci numbers of {} terms are {}'.format(n, fibonacci_numbers))

    even_sum = 0
    for n in fibonacci_numbers:
        if n % 2 == 0:
            even_sum += n

    print('Sum of even numbers is {}'.format(even_sum))

def fibonacci_upto(n):
    a, b = 1, 2
    fibonacci_numbers = []
    while a < n:
        fibonacci_numbers.append(a)
        a, b = b , a + b
    print('Fibonacci numbers up to {} term are {}'.format(n, fibonacci_numbers))
    even_sum = 0
    for n in fibonacci_numbers:
        if n % 2 == 0:
            even_sum += n
    print('Even numbers sum is {}'.format(even_sum))

#fibonacci(10)
#fibonacci_upto(100)
#fibonacci_upto(4000000)
