"""

Project Euler 44: Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, …

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and
 D = |Pk − Pj| is minimised; what is the value of D?


"""

def run():
    ps = set()
    i = 1000
    while True:
		
        i += 1
        pent = (3*i*i - i) // 2
        for Pj in ps:
            if pent - Pj in ps and pent - 2*Pj in ps: 
                return pent - 2*Pj
        ps.add(pent)

print(" the value of d is: ",run())
